import discord

colors = [
    discord.color.blue(),
    discord.color.blurple(),
    discord.color.brand_green(),
    discord.color.brand_red(),
    discord.color.dark_blue(),
    discord.color.dark_gold(),
    discord.color.dark_gray(),
    discord.color.dark_green(),
    discord.color.dark_grey(),
    discord.color.dark_magenta(),
    discord.color.dark_orange(),
    discord.color.dark_purple(),
    discord.color.dark_red(),
    discord.color.dark_teal(),
    discord.color.dark_theme(),
    discord.color.darker_gray(),
    discord.color.darker_grey(),
    discord.color.default(),
    discord.color.fuchsia(),
    discord.color.gold(),
    discord.color.green(),
    discord.color.greyple(),
    discord.color.light_gray(),
    discord.color.light_grey(),
    discord.color.lighter_gray(),
    discord.color.lighter_grey(),
    discord.color.magenta(),
    discord.color.og_blurple(),
    discord.color.orange(),
    discord.color.purple(),
    discord.color.random(),
    discord.color.red(),
    discord.color.teal(),
    discord.color.yellow()
]